<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Job Seeker</name>
   <tag></tag>
   <elementGuidId>fa57e95b-1322-43f3-8a1a-48921553995b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav-accordion']/li[6]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>798f3795-0dc9-43af-850b-5adcaf4c0ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d6a4117a-2b9a-4599-8e15-b8aaa07be179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jobseekers/new</value>
      <webElementGuid>e377b1d9-cc5f-423b-8aed-af83aa2565a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Job Seeker</value>
      <webElementGuid>33fc78e7-050c-44c7-9b67-e1eab18d4c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-accordion&quot;)/li[@class=&quot;sub-menu dcjq-parent-li&quot;]/ul[@class=&quot;sub&quot;]/li[1]/a[1]</value>
      <webElementGuid>6efdb4a2-b924-464f-80f7-008b0b89fc94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav-accordion']/li[6]/ul/li/a</value>
      <webElementGuid>e7d8c856-f207-46e4-9a03-cfeaacdcbacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Job Seeker')]</value>
      <webElementGuid>db67a39f-873c-442a-92ea-ae41ff626e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jobseekers/new')]</value>
      <webElementGuid>6c8e05a7-910b-4041-b9aa-e99e9d038fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li/a</value>
      <webElementGuid>6bb5a9dd-4aca-4d4f-af06-3e347d7646ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/jobseekers/new' and (text() = 'New Job Seeker' or . = 'New Job Seeker')]</value>
      <webElementGuid>35fd852e-2974-42e5-b146-e536132ac23f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
