<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_jobseekerfirst_name</name>
   <tag></tag>
   <elementGuidId>9925ce29-9a4e-4ada-87d4-ad1c61bdc26b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobseeker_first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobseeker_first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a83d28ee-f341-450f-bd1a-eb53fed70c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control string required form-control</value>
      <webElementGuid>6f100b2c-ce6c-44fc-9e92-f0a6ba744376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>jobseeker.firstName</value>
      <webElementGuid>3de8332c-7979-43c3-8668-99b067c71370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>7dd4ff63-a76c-4ad9-b865-03a520f8ef4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filter-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ceefbc9f-4f2d-401e-9401-d5751dc8f5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-property</name>
      <type>Main</type>
      <value>first_name_not_analyzed</value>
      <webElementGuid>e978aa59-a6e6-46e0-b3cf-4b6f0d61caa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index-property</name>
      <type>Main</type>
      <value>first_name</value>
      <webElementGuid>108236b2-4657-4e62-abb3-4fea7be765b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>89f4e095-be8d-4944-bf02-4d31d312b315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f0268dd2-61f2-450c-82e1-f65ac6974731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a5584a1-4c2a-42c3-a243-d22e72d6ae66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobseeker[first_name]</value>
      <webElementGuid>c46849ff-9329-4187-aa57-58dd7526bd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobseeker_first_name</value>
      <webElementGuid>ba5b2d22-448f-4a05-b986-b73f74c47aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobseeker_first_name&quot;)</value>
      <webElementGuid>1ea5ff5d-959a-4f55-8953-382a2d9f6a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobseeker_first_name']</value>
      <webElementGuid>3fe0f1fd-5b9c-4974-89f8-a6733573dbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_jobseeker']/div/div[3]/div[2]/div/input</value>
      <webElementGuid>2953bab0-1475-4afc-a025-fea330860b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>224f9fa0-735f-4a04-94c1-e99d30a0883d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobseeker[first_name]' and @id = 'jobseeker_first_name']</value>
      <webElementGuid>41f7ee3f-ff6f-4b43-a866-fdd88110c471</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
