<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_jobseekeress_identifier</name>
   <tag></tag>
   <elementGuidId>0ac655b4-fab5-499e-97a0-3d092f2b0ea2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobseeker_ess_identifier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobseeker_ess_identifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30933203-1180-440a-be1a-aad6faec7572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control string optional form-control</value>
      <webElementGuid>ce43c330-e900-4e10-87b8-79c3563b9f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>jobseeker.essIdentifier</value>
      <webElementGuid>3ea3cb89-6697-4fd7-aae9-a28ae062fc52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>lazy_multi_select</value>
      <webElementGuid>18e76065-0878-4864-bc88-8d5163ad0e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-property</name>
      <type>Main</type>
      <value>ess_identifier_not_analyzed</value>
      <webElementGuid>4e633b9d-13cc-4118-a9ad-494c873fe398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unique</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93be9f98-67a6-4932-b4e3-ee8986328673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a7795674-4a96-4215-b1f7-dd2f2e79c1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3f9ed29-a521-4f52-a960-032b7096f384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobseeker[ess_identifier]</value>
      <webElementGuid>2f94a8c4-1d38-414d-9690-2338b9d7682a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobseeker_ess_identifier</value>
      <webElementGuid>ab178d7a-122e-4d16-bcb6-07f7f26f3785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobseeker_ess_identifier&quot;)</value>
      <webElementGuid>78d14a05-5836-41bc-84f5-6fc8e84a3bfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobseeker_ess_identifier']</value>
      <webElementGuid>cfa5a1c5-f368-490e-9208-04c0bc2d0df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_jobseeker']/div/div/div[3]/div/input</value>
      <webElementGuid>43905514-ccf3-49bf-b212-d814e72252a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>ebab9baf-fab9-4383-b49d-ef1f3854c493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobseeker[ess_identifier]' and @id = 'jobseeker_ess_identifier']</value>
      <webElementGuid>d53e4b89-a5cb-42bd-bd8e-9cd6d2157a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
