<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_jobseekerlast_name</name>
   <tag></tag>
   <elementGuidId>487efda9-ca6a-4938-b7e0-07df4de86631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobseeker_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobseeker_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22ccb10d-61bf-4329-8c0d-a7035469f43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control string required form-control</value>
      <webElementGuid>d8df13c3-e133-4fec-8625-669a71241fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>jobseeker.lastName</value>
      <webElementGuid>4523fe73-2890-446f-a598-b4926257f386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>2f932f8f-f6f0-49f0-a1e7-0b2338cbcbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-filter-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e478d0e2-915a-4880-a7f8-3086777bb3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-property</name>
      <type>Main</type>
      <value>last_name_not_analyzed</value>
      <webElementGuid>2730cc6b-2cf6-435d-a74f-1aa538025d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index-property</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>1d31aa2e-0c45-4db3-8c24-a4d63c36a4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>1c0cda1c-434e-4294-bfb4-ecd881919fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76a4a6e6-c23e-42e6-a5de-4b1d5157ab81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b571cd9-4755-46b1-9c04-48a02cb51abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobseeker[last_name]</value>
      <webElementGuid>aa9822ce-eaa4-492e-b6e4-71937ee0d331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobseeker_last_name</value>
      <webElementGuid>35cb256b-367f-4f7d-9f6a-380ba92a1320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobseeker_last_name&quot;)</value>
      <webElementGuid>8bf16647-2fef-470a-9e92-282a08d763aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobseeker_last_name']</value>
      <webElementGuid>ca2f06f8-747a-4de2-928a-85f549ef6968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_jobseeker']/div/div[3]/div[4]/div/input</value>
      <webElementGuid>659b765d-8e18-4506-9eac-27802d52a1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>1efe1b90-341d-42e3-a3ae-80bd04c30d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobseeker[last_name]' and @id = 'jobseeker_last_name']</value>
      <webElementGuid>d064efd1-c28d-4e3e-a433-4e73d9414e48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
