<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Job Seekers</name>
   <tag></tag>
   <elementGuidId>303b09a2-9759-4818-8f28-c0246bc155af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav-accordion']/li[6]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4c01d745-3a74-4fcd-a13a-9e60fa8687e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job Seekers</value>
      <webElementGuid>28663b51-160e-4710-b2d8-b4e226550138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-accordion&quot;)/li[@class=&quot;sub-menu dcjq-parent-li&quot;]/a[@class=&quot;dcjq-parent&quot;]/span[2]</value>
      <webElementGuid>7cbe9bd9-3db0-42d1-a64b-ba7596d08ce0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='nav-accordion']/li[6]/a/span[2]</value>
      <webElementGuid>c0c18bda-b0e0-4c06-8d1c-f07a49828d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span[2]</value>
      <webElementGuid>77ee204a-7637-4033-804b-661e880b325d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Job Seekers' or . = 'Job Seekers')]</value>
      <webElementGuid>5aa5494a-4edc-436e-ba89-d09e83f8edf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
